name: Test
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  test:
    name: CppCheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          tool: 'CppCheck'
          input_file: 'test/test.xml'
          sarif_file: 'test.sarif'
      - run: |
          cat test.sarif
      - name: check SARIF output
        run: |
          import json
          with open('test.sarif') as fh:
            sarif = json.load(fh)
          results = sarif['runs'][0]['results']
          assert set(r['ruleId'] for r in results) == {'uninitvar', 'missingIncludeSystem'}
          assert sarif['runs'][0]['tool']['driver']['name'] == 'CppCheck'
        shell: python
