name: Test
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  test:
    name: CppCheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          tool: 'CppCheck'
          input_file: 'test/test.xml'
          sarif_file: 'test.sarif'
      - run: |
          cat test.sarif
